groups/urls.py
# GROUPS URLS.PY
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.ListGroups.as_view(), name = 'all'),
    path("new/", views.CreateGroup.as_view(), name = 'create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(), name = 'single'),
    #2:30 this will say posts/in and then slugify the actual group name and then it will lead to the actual group
    path('posts/join/<slug>/', views.JoinGroup.as_view(), name = 'join'),
    path('posts/leave/<slug>/', views.LeaveGroup.as_view(), name = 'leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name = 'all'),
    path("posts/new/", views.CreatePost.as_view(), name = 'create'),
    path("by/<username>/",views.UserPosts.as_view(),name = "for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name = "single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name = "delete"),
]

# 19:30 if get_context data or  get_queryset in post's views.py was hard to understand see documentation
# you will use these methods more as you get more advanced with Django
# you can use class based views without these methods but its only when you start getting more advanced or want extra
# funactionality will you end up adding one extra methods
# but alot of functionality we'll use for our own projects will probably at the start work just fine with class bsaed views

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    # 10:30 the above line connects the accounts namespace to accounts.urls so if someone has login our logout
    # it connects to the urls file we just made in the accounts application
    path('accounts/', include("django.contrib.auth.urls")),
    # the above line will allow us to connect everything django has under the hood for authentication
    # 11:00 under the account admin since we're using django's built in models we dont actually have to register anything
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),

    
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# what slugify does is it allows us to remove any characters
# that aren't alphanumeric, underscore, or hyphens
# 1:01 the idea is basically if you have a string that has spaces and
# you want to use it as part of the url, its going to be able to lowercase and add dashes instaed of spaces
# that way it works with your browser
import misaka
# 1:10 allows us to put links or markdown text, like reddit
from django.contrib.auth import get_user_model
User = get_user_model()
# 2:10 this allows us to call thing off of the current user's session
from django import template
register = template.Library()
# 2:40 this will be explained later but it is how you can use custom template tags

class Group(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    #6:00 explains what slug is but i think it's just for no mistakes when calling the url code
    description = models.TextField(blank = True, default = '')
    description_html = models.TextField(editable = False, default = '', blank = True)
    # 7:20 we may want an html version of our description
    members = models.ManyToManyField(User, through = 'GroupMember')
    # 10:40 many to many field is just all the members that belong to this group

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # 8:30 this means we can have spaces in the name but when we actually save it
        # the slug will become the slugify on self.name which just replaces and lowercases things
        self.description_html = misaka.html(self.description)
        # 9:00 incase we have markdown in the description i can call it with my html
        super().save(*args, **kwargs) 
    
    def get_absolute_url(self):
        return reverse('groups:single', kwargs = {'slug':self.slug})
    
    class Meta:
        ordering = ['name']
        

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name = 'memberships', on_delete = models.CASCADE)
    # 4:00 tis means the groupmember is related to the group class through the foreign key
    user = models.ForeignKey(User, related_name='user_groups',on_delete = models.CASCADE)
    # 4:18 we get the user from the User = get_user_model()

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render
from django.contrib import messages
# Create your views here.
from django.contrib.auth.mixins import (LoginRequiredMixin, 
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic

from groups.models import Group, GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group
    # 1:40 for a create view we need to specifcy the fields they should be able to create
    # and link it up to the model


class SingleGroup(generic.DetailView):
    # this will just be details of a specific group like the posts inside the group
    model = Group
    # just link it up to the model for a detailview

# when someone goes to the listgroups page they will see a list of all the available groups
# its like a list of subreddits
class ListGroups(generic.ListView):
    model = Group
    # just need to link it up to the model
    
# 1:10 a person should be logged in to join a group and when someone clicks on join
# we do stuff on the back end of our models to join the actual user to be a group member of that group and then
# redirect to another page
class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs = {'slug':self.kwargs.get('slug')})
        # 2:30 basically get the slug for the page we're clicking the button of the join group of
        # 2:00 groups:single is the detail view of that group
        # 2:10 to know which groups we're talking about we add in kwargs

    # this method is just to make sure the person gets an error if they already a member of the group
    # so we try to create a new member, if they are member already tell them they are, if they arent a member
    # make them a member and tell them they became a member using django messages
    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug = self.kwargs.get('slug'))
        # 3:05 try to get the group this person is looking at or return a 404 page, is what the above line does
        
        # 4:20 try to create a group member where user is the current user and group is the group
        # thats what the line under the try does
        try:
            GroupMember.objects.create(user = self.request.user, group = group)
            # basically the above line creates a group member
        
        except IntegrityError:
            messages.warning(self.request, ('Warning already a member!'))

        else:
            messages.success(self.request, ('You are now a member!'))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs = {'slug':self.kwargs.get('slug')})

    # make sure they cant leave a group if they arent in it
    def get(self, request, *args, **kwargs):
        try:
            # 8:40 try to get a membership off the group member assuming the user is
            # already in that group,
            membership = models.GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get('slug')
                ).get()
        # expect if the member wasn't actually a member of that group
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        # if everything is working then delete the user from the group
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)
        
        

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
    <div class = "container">
        <div class = "row">
            {% block pregroup %} {% endblock %}
            {% block group_content %} {% endblock %}
            {% block postgroup %} {% endblock %}
            <!-- may not always need to use all three of these blocks
            but this is just incase we want something before the group content,
            during the group content, and after the group content -->
        </div>
    </div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}

<h1>{{group.name}}</h1>
<!-- 5:34 remember that with class based views a context dictionary gets passed that holds everything that
the model has -->
<!-- since group has a name attribute i can just call group.name (the lower case version of the model name) -->
<h2>Member Count: {{group.members.count}}</h2>
<!-- 6:20 model has a members so we call group.members and if we do group.members.counts
we can get a count of all the members, this is something we didnt define but have access to this method
check documentation for various things you can call off model objects -->

<div class = "content">

    {% if user in group.members.all %} 
    <!-- 7:10 this basically means if the user is inside this array/list
    of all the members inside of the group model do the following -->
    <a href="{% url 'groups:leave' slug=group.slug %}" 
    class = 'btn btn-lg btn-fill btn-warning'><span 
    class = 'glyphicon glyphicon-remove-circle'></span>Leave</a>
    <!-- 7:55 he doesnt say what its for but i guess its related to making the url work since slug fixes the urls i think
    he says we will edit it later on -->
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" 
    class = 'btn btn-lg btn-fill btn-warning'><span 
    class = 'glyphicon glyphicon-ok-circle'></span>Join</a>
    {% endif %}

</div>

{% endblock %}

{% block group_content %}
<!--  we dont want the group content (the list of actual posts to take up the entire page, we
want them lined up abit -->
<div class = "col-md-8">
    <!-- if the group has no posts say there is no posts in the group -->
    {% if group.posts.count == 0 %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
            <!-- 12:00 include is like saying extends but we insert/inject it right in the middle of an html file -->
            <!-- since posts has alot of stuff going on like alot of html calls, template calls, template tags,
            i dont want to include it all in the group_detail.html, instead we just take care of it in post.html
            since this is going to be injected we put the _ to signify as a developer that this will be injected
            dont need the underscore there it's just to tell me that this piece of html will be injected into other html files
            using include -->
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new group!</h4>
    <form action="{% url 'groups:create' %}" method="post" id ='groupForm'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- the above line just makes the form look nicer usin bootstrap 3 -->
        <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

<!-- 24:00 basically this page give you a list of avaiable groups, the group name, a group description
the number of members in that group, the number of posts in that group -->
{% block pregroup %}
    <div class = "col-md-4">
        <div class = "content">
            {% if user.is_authenticated %}
            <!-- 14:00 can say if user.is_authenticated becasue of the django.auth package
             it takes care of all the heavy lifting on the back end-->
            <h2>Welcome Back!
                <a href="{% url 'posts:for_user' username=user.username %}">
                    @{{user.username}}
                    <!-- if you click the @username link like twitter it will take you to a list of all your posts
                    
                     -->
                </a>
            </h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>
        {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class = 'btn btn-md btn-fill btn-warning'>
            <!-- 16:20 the user can createa  group from any page since its on the navagation bar but
            if we are on the group page it might be a good idea to have a button again -->
            <span class = 'glyphicon glyphicon-plus-sign'>Create New Group!</span>
        </a>
        {% endif %}
    </div>
{% endblock %}

<!-- 23:05 what this code does -->
{% block group_content %}
<div class = "col-md-8">
    <div class = "list-group">
        <!-- for a list of the actual groups, have a link to the actual group name
        so if you click on that group name it takes you to that group's single page through the slug connection -->
        {% for group in object_list %}
        <a class = "list-group-item" href="{% url 'groups:single' slug=group.slug %}">
            <h3 class = 'title list-group-item-heading'>{{group.name}}</h3>
            <!-- clicking group name wil ltake you to the groups page -->
            <div class = "list-group-item-text container-fluid">
                {{group.description_html|safe}}
                <!-- we also dont just display the group.name but also a description of the group
                 -->
                <!-- 20:00 from last lecture this just makes sure that if we have bold html we get the text bolded
                instead of seeing the bold tags, it doesnt have to be bold can apply to all html, even for things like
                italics -->
                <div class = "row">
                    <div class = "col-md-4">
                        <!-- display the number of members in the group -->
                        <span class = "badge">{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class = "col-md-4">
                        <!-- display the number of posts in the group -->
                        <span class = "badge">{{group.posts.count}}</span>
                        post{{group.posts.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}