posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name = 'all'),
    path("posts/new/", views.CreatePost.as_view(), name = 'create'),
    path("by/<username>/",views.UserPosts.as_view(),name = "for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name = "single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name = "delete"),
]

# 19:30 if get_context data or  get_queryset in post's views.py was hard to understand see documentation
# you will use these methods more as you get more advanced with Django
# you can use class based views without these methods but its only when you start getting more advanced or want extra
# funactionality will you end up adding one extra methods
# but alot of functionality we'll use for our own projects will probably at the start work just fine with class bsaed views

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    # 10:30 the above line connects the accounts namespace to accounts.urls so if someone has login our logout
    # it connects to the urls file we just made in the accounts application
    path('accounts/', include("django.contrib.auth.urls")),
    # the above line will allow us to connect everything django has under the hood for authentication
    # 11:00 under the account admin since we're using django's built in models we dont actually have to register anything
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),

    
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()
# this will just connect hte current post to whoever is logged in as a user

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now = True)
    # 13:00 auto_now = True means we dont have to put in the time it will be done automatically when the user posts
    message = models.TextField()
    message_html = models.TextField(editable = False)
    group = models.ForeignKey(Group, related_name = 'posts', null = True, blank = True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message
    
    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        # 15:10 this is so if someone writes in a markdown so they put a link in their post, it doesn't look with like a
        # strange notation of brackets and stuff, it is supported from the html from misaka
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs = {'username':self.user.username, 'pk':self.pk})
    # 16:20 we will use primary key as a way to relete the posts back to the url
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']
        # every message is uniquely linked to a user

posts/views.py
#POST VIEWS.PY
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()
# 2:30 basically the get_user_model import allows us to set a user object = to get_user_model
# and then call get_user_model, so if someone is logged into a session i can use the user object as
# the current user and then call things off of that
# Create your views here.
# 18:10 class postlist shows a list of posts related to either the user or the group
class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    # connect to the model
    select_related = ('user', 'group')
    # 3:30 this is a mixin that allows us to provide a tuple of related models which is the foreigne keys for this post
class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact = self.kwargs.get('username'))
            # 4:50 the prefetch_related is another method we can call off objects, see documentation
            # 5:30 basically we try to get the queryset which means it trys to set self.post.user that belongs to the post
            # to that user's object, then we will prefetch_related posts and get whereever the username is equal to the username
            # off who ever is logged in or whatever user you click on
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
        # all this method does is to make sure when you call the queryset for the user that the user actually exists
        # if they user doenst expect return  404 error, if the user does exist then just return a list of the user's posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(** kwargs)
        context['post_user'] = self.post_user
        return context
    # 7:38 return the context data object connected to whoever actually posted that specific user

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))
    # 9:20 similar to before, get the queryset for the actual post, and then filter where the username is equal to the
    # exact user's username, which us the username of the model's object

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        # 11:00 the right hand side of the = means the user that sent the request
        self.object.save()
        # 11:00 we are trying to connect the post to the user
        return super().form_valid(form)
    
class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')
    # 12:00 once we  delete the post go back to the list of all the posts

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)
    
    def delete(self,*args,**kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)
    # 13:30 alot of the stuff we do for delete view is a convention and not chosen  can look this up
    # in the documentation

posts/templates/posts/_post.html
<!-- 10:40 dont need to use extension because we use include when we want this injected -->
<div class = "post media">
    <h3 class="mr-5"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h3>    
    
    <div class = "media-body">
        <strong>{{post.user.username}}</strong>
        <h5 class = 'media-heading'>{{ post.message_html|safe }}
        <time class = 'time'><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
        </h5>
        
        <div class = "media-footer">
            <!-- if the user is logged in and the post is theirs then they can delete it -->
            {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title = "delete" class = "btn btn-simple">
                <span class = 'glyphicon glyphicon-remove text-danger' aria-hidden = 'true'></span>
                <!-- 16:05 aria stands for accessible rich internet applications and that defines a way to make
                web applications more accessiable to people with disabilities, so some people may have screen readers
                that read stuf for them if they hover over things, so this element tells browsers not to display the
                element and for screen readers not to read it -->
                <span class = 'text-danger icon-label'>Delete</span>
            </a>
            {% endif %}
        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class = "posts-page">
    <div class = "container">
        <div class = "row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>

</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class = "posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class = 'btn btn-danger btn-large'>
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" 
    class = 'btn btn-simple btn-large btn-default'>Cancel</a>
    <!-- basically we're saying if you want to delete this you can with the submit button
    if you dont want to delete this have a link that takes you back -->
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class ="col-md-8">
    {% include "posts/_post.html" %}
</div>

{% endblock %}

posts/templates/posts/post_form.html
<!-- 2:10 post_form is the html template linked to creating a new post -->
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
<h4>Create a new Post</h4>
<form id = "postForm" action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class = 'btn btn-primary btn-large'>
</form>

{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
<div class = "col-md-4">
    {% if request.user.is_authenticated %}
    <div class = "card card-with-shadow">
        <div class = "content">
            <h5 class = 'title'>Your Groups</h5>
            <ul class = 'list-unstyled'>
                {% for member_group in get_user_groups %}
                    <!-- 6:00 explains this but in models.py underneath groups we did
                     from django import template
                     register = template.library()
                     and then in the groupmember class we did
                     user = models.ForeignKey(User, related_name='user_groups',on_delete = models.CASCADE)
                     this allowed us to change the name for groupmember, so this allows us to do a link from
                     posts to the group member -->
                     <li class = 'group li-with-bullet'>
                        <a href="{% url 'groups:single' slug=member_group.group.slug %}"></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class = "card card-with-shadow">
        <div class = "content">
            <h5 class = 'title'>All Groups</h5>
            <ul class ='list-unstyled'>
                {% for other_group in get_other_groups %}
                    <li class = 'group li-with-bullet'>
                        <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block post_content %}
    <div class = "col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class = "col-md-4">
    <h1>@{{post_user.username}}</h1>

</div>
{% endblock %}

{% block post_content %}
<div class = "col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
    {% endfor %}
</div>
{% endblock %}